### PR TITLE
Fix soil drainage problem

### LINKED ISSUE #622: Problem with drainage class
**What's wrong**
- At Site Conditions page, with a selected drainage class, click next, then click back, the selected drainage class would drop 1 level.

**What done looks like**
- The drainage class should be the same

**Where the changes need to be made**
- Location/SoilCondition/SoilDrainage/RenderDrainageClasses.js

### PR DESCRIPTION
**Pull request by YazidZidane**
- Not allow soil drainage api runs every time enters the page to update soil drainage information. If a soil drainage value is selected, only show the selected value unless changed.
- Fixed a problem that sometime soil drainage value would not shown.
- Fixed a problem that soil drainage value would drop one level every time enter the page.

closes #622

### CODE REVIEW

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://48.217.199.95:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

**Comment by mikahpinegar** [comment]
Your review app has been deployed and is available at 'http://48.217.199.95:80'.<br><br>[Learn More](https://aka.ms/testwithreviewapps) about how to test and provide feedback for the app.

File: src/pages/Location/SoilCondition/SoilDrainage/RenderDrainageClasses.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ const RenderDrainageClasses = ({
   const historyStateRedux = useSelector((stateRedux) => stateRedux.userData.historyState);
 
   const [previousDrainage, setPreviousDrainage] = useState(-1);
-  const [updateTilingCheck, setUpdateTilingCheck] = useState(true);
+  const [updateTilingCheck, setUpdateTilingCheck] = useState(false);
```
Comment (mikahpinegar) [inline src/pages/Location/SoilCondition/SoilDrainage/RenderDrainageClasses.js:24]: this needs to be put in redux. selecting tiling as yes, then clicking next, and then back no longer shows tiling as yes

**Review by mikahpinegar — CHANGES_REQUESTED** [review]

File: src/pages/Location/SoilCondition/SoilDrainage/RenderDrainageClasses.js (hunk 1 above)
Comment (mikahpinegar) [reply src/pages/Location/SoilCondition/SoilDrainage/RenderDrainageClasses.js:24]: this will be a new issue

**Review by mikahpinegar — APPROVED** [review]
